"""Initial migration - create users and competitions tables

Revision ID: 3cb59d4dc88a
Revises: 
Create Date: 2025-07-11 22:25:01.495347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3cb59d4dc88a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'CREATOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('competitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
    sa.Column('scale', sa.Enum('LOCAL', 'REGIONAL', 'NATIONAL', 'INTERNATIONAL', name='competitionscale'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('registration_deadline', sa.Date(), nullable=False),
    sa.Column('prize_structure', sa.Text(), nullable=True),
    sa.Column('eligibility_criteria', sa.Text(), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('target_age_min', sa.Integer(), nullable=True),
    sa.Column('target_age_max', sa.Integer(), nullable=True),
    sa.Column('required_grade_min', sa.Integer(), nullable=True),
    sa.Column('required_grade_max', sa.Integer(), nullable=True),
    sa.Column('subject_areas', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_competitions_created_by'), 'competitions', ['created_by'], unique=False)
    op.create_index(op.f('ix_competitions_is_active'), 'competitions', ['is_active'], unique=False)
    op.create_index(op.f('ix_competitions_is_featured'), 'competitions', ['is_featured'], unique=False)
    op.create_index(op.f('ix_competitions_location'), 'competitions', ['location'], unique=False)
    op.create_index(op.f('ix_competitions_scale'), 'competitions', ['scale'], unique=False)
    op.create_index(op.f('ix_competitions_title'), 'competitions', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_competitions_title'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_scale'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_location'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_is_featured'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_is_active'), table_name='competitions')
    op.drop_index(op.f('ix_competitions_created_by'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
