"""Add featured_priority field to competitions table

Revision ID: d71093cb5ad5
Revises: 3cb59d4dc88a
Create Date: 2025-07-12 22:31:17.247163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd71093cb5ad5'
down_revision: Union[str, Sequence[str], None] = '3cb59d4dc88a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('competitions', sa.Column('featured_priority', sa.Integer(), nullable=True))
    
    # Set default value for existing records
    op.execute("UPDATE competitions SET featured_priority = 0 WHERE featured_priority IS NULL")
    
    # Make column NOT NULL
    op.alter_column('competitions', 'featured_priority', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('competitions', 'featured_priority')
    # ### end Alembic commands ###
